### PR TITLE
PhantomJS

### PR DESCRIPTION
**Pull request by ciscoheat**
Added PhantomJS support! I renamed `build-js.hxml` to `build-nodejs.hxml` to differentiate the js targets.

The naming convention for script files is now `.travis-TARGET-(install|script).sh` to follow the Travis convention.

I'm not 100% happy with the `src-phantomjs` directory, maybe you can find a location for those files that makes more sense? :)

### CODE REVIEW

**Comment by ciscoheat** [comment]
One more fix to do, brb

**Comment by ciscoheat** [comment]
Done, but appveyor is failing... I'm only using Travis, so I don't know how much must be modified?

**Comment by ciscoheat** [comment]
I'll make an attempt. Brb again!

**Comment by ciscoheat** [comment]
Ok done!

**Comment by andyli** [comment]
Great! I've merged.
Just one comment, I think it is better to replace all the bash scripts with haxe scripts (using `--run`). My point is that any haxe devs will definitely be able to read haxe code but may not be able to read bash. And in the CI env we've haxe installed anyway, so the script will be cross-platform by default.

**Comment by ciscoheat** [comment]
Do you mean executing the commands through a haxe script instead? And would the scripts be a full Haxe class, not hscript?

**Comment by andyli** [comment]
Yeah, full haxe classes calling commands, using the `--run` macro target. For example, ".travis-phantomjs-script.sh" may be convented to
```haxe
import Sys.*;
import sys.io.File.*;
using StringTools;

class PhantomScript {
	static function main() {
		var args = args();
		var jsFile = args[0];
		var tmpl = getContent("bin/phantomjs.html");
		var html = tmpl.replace("[PHANTOMJS]", jsFile);
		saveContent("bin/phantomjs.html", html);

		command("phantomjs", ["src-phantomjs/phantomjs.js"].concat(args.length > 1 ? [args[1]] : []));
	}
}
```
and then use it like
```
haxe --run PhantomScript path/to/js
```

If you wanna use a proper cmdline lib like mcli, we can have a hxml file
```
#PhantomScript.hxml
-cp ci_scripts
-lib mcli
--run PhantomScript
```
and then use it like
```
haxe PhantomScript.hxml path/to/js
```

What do you think?

**Comment by ciscoheat** [comment]
I hesitate to port the Unix tools... Since they are only used in CI environments for now, I'd rather make the scripts simple, well-commented and with a few useful parameters instead.

**Comment by andyli** [comment]
No problem :)
Probably I will convert them to Haxe later as I don't see the disadvantage of that.
Thanks for the PRs!

**Pull request merged**
