### PR TITLE
Flash support for Travis

### PR DESCRIPTION
**Pull request by ciscoheat**
Here are the Flash testing hoops I'm using for Buddy, seems to work fine for HaxeCI too: https://travis-ci.org/ciscoheat/HaxeCI

Anything you'd be interested in?

### CODE REVIEW

**Comment by andyli** [comment]
Cool! Didn't realize there is `flash.system.System.exit`. Thanks!

**Comment by ciscoheat** [comment]
Glad you like it. :) I'm thinking how to simplify the project structure. If you make a cross-platform library and want to test it on a selection of targets it would be nice to do it without having all those `hxml` files in the top directory doing basically the same thing?

**Comment by andyli** [comment]
I've been thinking about that too but I cannot come up with a better solution.
One problem is that Haxe codes are so flexible that they can be complied in so many different ways. Other than large number of targets, each target can have slightly different settings like `-D dll`, `-D js-classic`. I'm not sure if it is good to abstract it by using a build tool or a small haxe script, like:
```haxe
class Build {
    static function main():Void {
        switch(Sys.args()) {
            case ["flash"]:
                Sys.command("haxe", [/* bla bla bla */]);
    }
}
```
```
haxe --run Build flash
```

**Comment by ciscoheat** [comment]
Yes, those small variations can really make things unwieldy. I was thinking of a build tool that generates the `hxml` files, but same problem there when you want to modify it. 

Maybe it's not too big of a problem, if it only affects cross-platform libraries. Not too many of those. :)

**Pull request merged**
